/**
 * Clash Royale Card Helper utilities.
 * 
 * Card data (rarity, elixir cost) is loaded from cards_static.json,
 * which is automatically updated by the GitHub Action from cr-api-data.
 */

// Static card data fallback type
interface CardStaticEntry {
  name: string;
  elixirCost: number;
  rarity: string;
  maxLevel: number;
  maxEvolutionLevel: number;
  iconUrls?: { medium?: string; evolutionMedium?: string };
}

interface CardsStaticData {
  updatedAt: string;
  totalCards: number;
  cards: Record<string, CardStaticEntry>;
}

// Load static card data (generated by update-meta.js from cr-api-data)
let cardsStaticData: CardsStaticData | null = null;

function getCardsData(): CardsStaticData {
  if (cardsStaticData) return cardsStaticData;

  try {
    // Dynamic import to allow the file to be missing during initial setup
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    cardsStaticData = require("@/data/cards_static.json") as CardsStaticData;
  } catch {
    // Fallback: return empty data if file doesn't exist yet
    console.warn("[cardHelpers] cards_static.json not found. Using fallback defaults.");
    cardsStaticData = { updatedAt: "", totalCards: 0, cards: {} };
  }

  return cardsStaticData;
}

/**
 * Returns the rarity of a card based on its ID.
 * Data source: cards_static.json (from cr-api-data).
 */
export const getCardRarity = (card: { id: number; name?: string }): "champion" | "legendary" | "epic" | "rare" | "common" => {
  const data = getCardsData();
  const entry = data.cards[String(card.id)];

  if (entry && entry.rarity) {
    const rarity = entry.rarity.toLowerCase();
    if (rarity === "champion") return "champion";
    if (rarity === "legendary") return "legendary";
    if (rarity === "epic") return "epic";
    if (rarity === "rare") return "rare";
    return "common";
  }

  // Fallback: Champion ID range detection (28000000+ series for some champions)
  if (card.id >= 26000085 && card.id <= 26000099) return "champion";

  return "common";
};

/**
 * Returns the elixir cost of a card based on its ID.
 * Data source: cards_static.json (from cr-api-data).
 */
export const getCardElixir = (id: number): number => {
  const data = getCardsData();
  const entry = data.cards[String(id)];

  if (entry && entry.elixirCost > 0) {
    return entry.elixirCost;
  }

  // Fallback default: 3 elixir (reasonable average)
  return 3;
};

/**
 * Calculates the average elixir cost for a list of cards.
 */
export const getAverageElixir = (cards: { id: number }[]): string => {
  if (!cards || cards.length === 0) return "0.0";
  const total = cards.reduce((sum, card) => sum + getCardElixir(card.id), 0);
  return (total / cards.length).toFixed(1);
};

/**
 * Checks if a card has an evolution available based on static data.
 */
export const hasEvolution = (id: number): boolean => {
  const data = getCardsData();
  const entry = data.cards[String(id)];
  return entry ? (entry.maxEvolutionLevel || 0) > 0 : false;
};

/**
 * Returns the card name from static data.
 */
export const getCardName = (id: number): string => {
  const data = getCardsData();
  const entry = data.cards[String(id)];
  return entry ? entry.name : `Card #${id}`;
};
